venvs/iot_server/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('iot/', include('iot.urls')),
]

venvs/iot_server/iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
  path('mqtt/', TemplateView.as_view(template_name='iot/mqtt.html'), name='mqtt'),
]

venvs/iot_server/iot_server/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('iot/', include('iot.urls')),
]

venvs/iot_server/iot_server/iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
  path('mqtt/', TemplateView.as_view(template_name='iot/mqtt.html'), name='mqtt'),
]

venvs/iot_server/iot/models.py
from django.db import models


class Sensor(models.Model):
  place = models.CharField(max_length=50)     # 설치 장소
  category = models.CharField(max_length=50)  # 센서 종류
  value = models.FloatField()                 # 센서 값
  created_at = models.DateTimeField()         # 측정 날짜-시간

venvs/iot_server/iot_server/iot/models.py
from django.db import models


class Sensor(models.Model):
  place = models.CharField(max_length=50)     # 설치 장소
  category = models.CharField(max_length=50)  # 센서 종류
  value = models.FloatField()                 # 센서 값
  created_at = models.DateTimeField()         # 측정 날짜-시간

venvs/iot_server/iot/views.py
from django.shortcuts import render
from . import sub

venvs/iot_server/iot_server/iot/views.py
from django.shortcuts import render
from . import sub

venvs/iot_server/iot_server/kakao/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
# from kakao.forms import KaKaoTalkForm
import json
import requests
from django.contrib import messages
client_id = "85bc3c0185aee494dedacd1cc7f82c33" # 자신의 REST KEY
class KakaoLoginView(TemplateView):
template_name = "kakao_login.html"
def get_context_data(self, **kwargs):
context = super().get_context_data(**kwargs)
context["client_id"] = client_id
return context

venvs/iot_server/iot_server/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap.min.css' %}"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    {% block style %}{% endblock %}
  </head>

  <body>
    {% include "navbar.html" %}
    <div class="container p-3">{% block content %}{% endblock %}</div>

    <script src="{% static 'jquery-3.6.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>

    {% block script %}{% endblock script %}
  </body>
</html>

venvs/iot_server/iot_server/templates/iot/mqtt.html
{% extends 'base.html' %} {% load static %} {% block content%}
<img src="{%static '/images/mqtt-logo.svg'%}" height="40" />
<div>
  <p>토픽: <input type="text" id="topic" /></p>
  <p>message: <input type="text" id="message" /></p>
  <button type="button" id="publish-btn" class="btn btn-primary">
    <i class="fas fa-paper-plane"></i> 전송
  </button>
</div>
<hr />
<div>
  <h2>거실</h2>
  <ul>
    <li>온도: <input type="text" id="temp" /></li>
    <li>습도: <input type="text" id="humi" /></li>
    <li>조도: <input type="text" id="illu" /></li>
  </ul>
</div>

{% endblock %} {% block script%}
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js"
  type="text/javascript"
></script>

<script>
  let btn = document.getElementById('publish-btn');
  let inputTopic = document.getElementById('topic');
  let inputMessage = document.getElementById('message');

  const BROKER_IP = 'localhost';
  const BROKER_PORT = 9001;
  const CLIENT_ID = 'clientID-' + parseInt(Math.random() * 100);
  const SUBSCRIBE_TOPIC = 'iot/#';

  client = new Paho.MQTT.Client(BROKER_IP, BROKER_PORT, CLIENT_ID);
  console.log(BROKER_IP, BROKER_PORT, CLIENT_ID);

  client.onConnectionLost = onConnectionLost; // 연결 끊김 콜백
  client.onMessageArrived = onMessageArrived; // 메시지 도착 콜백

  client.connect({
    onSuccess: onConnect, // 연결 성공시 호출 콜백
    onFailure: onFailure, // 연결 실패시 호출 콜백
  });

  function onConnectionLost(responseObject) {
    if (responseObject.errorCode !== 0) {
      console.log('onConnectionLost:' + responseObject.errorMessage);
    }
  }

  let temp = document.getElementById('temp');
  let humi = document.getElementById('humi');
  let illu = document.getElementById('illu');

  function onMessageArrived(message) {
    let topic = message.destinationName;
    let value = message.payloadString;
    const [_, place, category] = topic.split('/'); // 배열 분해 할당
    if (category == 'temp') temp.value = value;
    else if (category == 'humi') humi.value = value;
    else if (category == 'illu') illu.value = value;
  }

  function onFailure() {
    alert('Please enter host and port again.');
  }

  function onConnect() {
    console.log('onConnect');
    client.subscribe(SUBSCRIBE_TOPIC);
  }

  btn.onclick = () => {
    const topic = inputTopic.value;
    const message = new Paho.MQTT.Message(inputMessage.value);

    message.destinationName = topic;
    message.qos = 1;
    client.send(message);
  };
</script>
{% endblock %}

venvs/iot_server/iot_server/templates/navbar.html
{% load static %}
<nav
  class="navbar navbar-expand-lg navbar-light bg-light border-bottom sticky-top"
>
  <a class="navbar-brand" href="#">
    <img src="{% static '/images/iot.png'%}" width="32" />
    IoT
  </a>
  <button
    class="navbar-toggler ml-auto"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'iot:mqtt'%}">
          <i class="fas fa-wifi"></i>
          MQTT
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-chart-bar"></i>
          통계
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-video"></i>
          mjpeg
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'iot:list'%}">
          <i class="fas fa-file-video"></i>
          보안 카메라
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="far fa-comment-alt"></i>
          카톡
        </a>
      </li>
    </ul>
  </div>
</nav>

venvs/iot_server/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap.min.css' %}"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    {% block style %}{% endblock %}
  </head>

  <body>
    {% include "navbar.html" %}
    <div class="container p-3">{% block content %}{% endblock %}</div>

    <script src="{% static 'jquery-3.6.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>

    {% block script %}{% endblock script %}
  </body>
</html>

venvs/iot_server/templates/iot/mqtt.html
{% extends 'base.html' %} {% load static %} {% block content%}
<img src="{%static '/images/mqtt-logo.svg'%}" height="40" />
<div>
  <p>토픽: <input type="text" id="topic" /></p>
  <p>message: <input type="text" id="message" /></p>
  <button type="button" id="publish-btn" class="btn btn-primary">
    <i class="fas fa-paper-plane"></i> 전송
  </button>
</div>
<hr />
<div>
  <h2>거실</h2>
  <ul>
    <li>온도: <input type="text" id="temp" /></li>
    <li>습도: <input type="text" id="humi" /></li>
    <li>조도: <input type="text" id="illu" /></li>
  </ul>
</div>

{% endblock %} {% block script%}
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js"
  type="text/javascript"
></script>

<script>
  let btn = document.getElementById('publish-btn');
  let inputTopic = document.getElementById('topic');
  let inputMessage = document.getElementById('message');

  const BROKER_IP = 'localhost';
  const BROKER_PORT = 9001;
  const CLIENT_ID = 'clientID-' + parseInt(Math.random() * 100);
  const SUBSCRIBE_TOPIC = 'iot/#';

  client = new Paho.MQTT.Client(BROKER_IP, BROKER_PORT, CLIENT_ID);
  console.log(BROKER_IP, BROKER_PORT, CLIENT_ID);

  client.onConnectionLost = onConnectionLost; // 연결 끊김 콜백
  client.onMessageArrived = onMessageArrived; // 메시지 도착 콜백

  client.connect({
    onSuccess: onConnect, // 연결 성공시 호출 콜백
    onFailure: onFailure, // 연결 실패시 호출 콜백
  });

  function onConnectionLost(responseObject) {
    if (responseObject.errorCode !== 0) {
      console.log('onConnectionLost:' + responseObject.errorMessage);
    }
  }

  let temp = document.getElementById('temp');
  let humi = document.getElementById('humi');
  let illu = document.getElementById('illu');

  function onMessageArrived(message) {
    let topic = message.destinationName;
    let value = message.payloadString;
    const [_, place, category] = topic.split('/'); // 배열 분해 할당
    if (category == 'temp') temp.value = value;
    else if (category == 'humi') humi.value = value;
    else if (category == 'illu') illu.value = value;
  }

  function onFailure() {
    alert('Please enter host and port again.');
  }

  function onConnect() {
    console.log('onConnect');
    client.subscribe(SUBSCRIBE_TOPIC);
  }

  btn.onclick = () => {
    const topic = inputTopic.value;
    const message = new Paho.MQTT.Message(inputMessage.value);

    message.destinationName = topic;
    message.qos = 1;
    client.send(message);
  };
</script>
{% endblock %}

venvs/iot_server/templates/navbar.html
{% load static %}
<nav
  class="navbar navbar-expand-lg navbar-light bg-light border-bottom sticky-top"
>
  <a class="navbar-brand" href="#">
    <img src="{% static '/images/iot.png'%}" width="32" />
    IoT
  </a>
  <button
    class="navbar-toggler ml-auto"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'iot:mqtt'%}">
          <i class="fas fa-wifi"></i>
          MQTT
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-chart-bar"></i>
          통계
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-video"></i>
          mjpeg
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'iot:list'%}">
          <i class="fas fa-file-video"></i>
          보안 카메라
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="far fa-comment-alt"></i>
          카톡
        </a>
      </li>
    </ul>
  </div>
</nav>